### ISSUE TITLE
Some proxy disabling https (Heroku?)

### ISSUE THREAD

**Issue by gyfis** [jstastny/webhookbin#1]
`req.protocol` returns `http` in all cases for this app. Related [stackOverflow](https://stackoverflow.com/questions/40459511/in-express-js-req-protocol-is-not-picking-up-https-for-my-secure-link-it-alwa). As per the answer, solution might be to add `app.enable('trust proxy');` somewhere.

**Comment by jstastny** [comment]
Thanks for reporting. Fixed using the `trust proxy` settings as you suggested in the comment.
